version: '3'

services:
  backend:
    restart: always
    build: ./Juridico_back
    ports:
      - 8000:8000
    container_name: juridico_back
    environment:
      REDIS_HOST: 'cache'

  frontend:
    restart: always
    build: ./Juridico_front
    ports:      
      - 4200:80
    links:
      - backend
    container_name: juridico_front
